/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: EddyNL (https://sketchfab.com/EddyNL)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/caterpillar-skid-steer-loader-859a64d242314ec3af5bfb449bdfa673
Title: Caterpillar Skid Steer Loader
*/

import React, { useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { useThree } from "@react-three/fiber";

export function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");

  let camera = useThree((state) => state.camera);
  let scene = useThree((state) => state.scene);

  useLayoutEffect(() => {
    let mm = gsap.matchMedia();

    mm.add(
      {
        isDesktop: `(min-width: 48em)`,
        isMobile: `(max-width:48em`,
      },
      (context) => {
        let { isMobile } = context.conditions;
        console.log(isMobile, "isMobile");
        const position = camera.position;

        const tl1 = gsap.timeline({
          scrollTrigger: {
            trigger: "#soundSection",
            start: "top bottom",
            end: "top top",
            scrub: 2,
            immediateRender: false,
          },
        });

        const tl2 = gsap.timeline({
          scrollTrigger: {
            trigger: "#displaySection",
            start: "top",
            end: "top top",
            scrub: 2,
            immediateRender: false,
          },
        });

        tl1
          .to(position, {
            x: isMobile ? -1 : -2,
            y: 0,
            z: isMobile ? 4 : 2,
          })
          .to(scene.rotation, { y: -2, x: 0.3, z: 0.3 })
          .to("#soundSectionLinks", {
            zIndex: 1,
          });

        tl2
          .to(position, {
            x: -1,
            y: -1,
            z: isMobile ? 4 : 2.5,
          })
          .to(scene.rotation, { y: -1, x:  isMobile ? 0 : -0.8, z: 0 });

        return () => {
          if (t1) t1.kill();
          if (t2) t2.kill();
        };
      }
    );
  }, []);

  return (
    <group {...props} dispose={null}>
      <group
        position={[380.82, 160.74, -2.68]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[45.72, 57.46, 57.46]}
      >
        <mesh
          geometry={nodes.Cabin_Plastic_matte001_0.geometry}
          material={materials["Plastic_matte.001"]}
        />
        <mesh
          geometry={nodes.Cabin_I_NEED_GREASE_TO_LIVE_0.geometry}
          material={materials.I_NEED_GREASE_TO_LIVE}
        />
      </group>
      <group
        position={[380.82, 108.95, -156.85]}
        rotation={[-1.64, 0, -Math.PI]}
        scale={[55.05, 42.1, 59.55]}
      >
        <mesh
          geometry={nodes.Engine_back_Plastic_matte_0.geometry}
          material={materials.Plastic_matte}
        />
        <mesh
          geometry={nodes.Engine_back_Rear_CAT_logo_black_0.geometry}
          material={materials.Rear_CAT_logo_black}
        />
      </group>
      <group
        position={[417.23, 175.09, 53.88]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[3.25, 1.96, 1.96]}
      >
        <mesh
          geometry={nodes.Hinge_high_Nuts_grey_0.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Hinge_high_Plastic_matte001_0.geometry}
          material={materials["Plastic_matte.001"]}
        />
      </group>
      <group
        position={[417.23, 144.69, 54.95]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[3.25, 1.96, 1.96]}
      >
        <mesh
          geometry={nodes.Hinge_low_Nuts_grey_0.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Hinge_low_Plastic_matte001_0.geometry}
          material={materials["Plastic_matte.001"]}
        />
      </group>
      <group
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      >
        <mesh
          geometry={nodes.Lift_cilinder_small_Nuts_grey_0.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={
            nodes.Lift_cilinder_small_Metal_black_a_bit_shiny_0.geometry
          }
          material={materials.Metal_black_a_bit_shiny}
        />
      </group>
      <group
        position={[380.82, 0, 13.58]}
        rotation={[-2.01, 0, -Math.PI]}
        scale={100}
      >
        <mesh
          geometry={nodes.Main_arm_Metal_yellow_0.geometry}
          material={materials.Metal_yellow}
        />
        <mesh
          geometry={nodes.Main_arm_Plastic_matte001_0.geometry}
          material={materials["Plastic_matte.001"]}
        />
      </group>
      <group
        position={[380.82, 0, 13.58]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={23.64}
      >
        <mesh
          geometry={nodes.NurbsPath005_Plastic_matte001_0.geometry}
          material={materials["Plastic_matte.001"]}
        />
        <mesh
          geometry={nodes.NurbsPath005_Rubber_black_0.geometry}
          material={materials.Rubber_black}
        />
        <mesh
          geometry={nodes.NurbsPath005_Rubber_yellow_0.geometry}
          material={materials.Rubber_yellow}
        />
      </group>
      <group
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      >
        <mesh
          geometry={nodes.Shovel_arm_wires002_Nuts_grey_0.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={
            nodes.Shovel_arm_wires002_Metal_black_a_bit_shiny_0.geometry
          }
          material={materials.Metal_black_a_bit_shiny}
        />
        <mesh
          geometry={nodes.Shovel_arm_wires002_Plastic_matte001_0.geometry}
          material={materials["Plastic_matte.001"]}
        />
      </group>
      <group
        position={[380.82, 0, 13.58]}
        rotation={[-1.4, 0, -Math.PI]}
        scale={100}
      >
        <mesh
          geometry={nodes.Shovel_pistolns_Metal_black_a_bit_shiny_0.geometry}
          material={materials.Metal_black_a_bit_shiny}
        />
        <mesh
          geometry={nodes.Shovel_pistolns_Nuts_grey_0.geometry}
          material={materials.material_0}
        />
      </group>
      <group
        position={[380.31, 0, 13.58]}
        rotation={[2.77, 0, 0]}
        scale={[-17.03, 17.03, 345.81]}
      >
        <mesh
          geometry={nodes.Side_main_lift_arm002_Nuts_grey_0.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={
            nodes.Side_main_lift_arm002_Metal_black_a_bit_shiny_0.geometry
          }
          material={materials.Metal_black_a_bit_shiny}
        />
      </group>
      <group
        position={[367.59, 212.63, 2.96]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={7.03}
      >
        <mesh
          geometry={nodes.Sphere_cover_0.geometry}
          material={materials.cover}
        />
        <mesh
          geometry={nodes.Sphere_Plastic_matte001_0.geometry}
          material={materials["Plastic_matte.001"]}
        />
      </group>
      <group
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      >
        <mesh
          geometry={nodes.Tires_Rubber_black_0.geometry}
          material={materials.Rubber_black}
        />
        <mesh
          geometry={nodes.Tires_Rubber_black_0_1.geometry}
          material={materials.Rubber_black}
        />
        <mesh
          geometry={nodes.Tires_Rubber_black_0_2.geometry}
          material={materials.Rubber_black}
        />
      </group>
      <group
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      >
        <mesh
          geometry={nodes.Tires_rims_Metal_yellow_0.geometry}
          material={materials.Metal_yellow}
        />
        <mesh
          geometry={nodes.Tires_rims_Metal_yellow_0_1.geometry}
          material={materials.Metal_yellow}
        />
      </group>
      <mesh
        geometry={
          nodes.Black_cutout_panel_rear_Metal_black_a_bit_shiny_0.geometry
        }
        material={materials.Metal_black_a_bit_shiny}
        position={[380.82, 0, 5.92]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Body_undercarriage_Metal_yellow_0.geometry}
        material={materials.Metal_yellow}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[77.6, 100, 100]}
      />
      <mesh
        geometry={nodes.Cabin_glass_front_Windows_0.geometry}
        material={materials.Windows}
        position={[378.29, 163.03, 51.7]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[44.86, 57.3, 56.38]}
      />
      <mesh
        geometry={nodes.Cabin_glass_rear_Windows_0.geometry}
        material={materials.Windows}
        position={[383.85, 185.83, -58.26]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[45.72, 57.46, 57.46]}
      />
      <mesh
        geometry={nodes.Cabin_glass_sides_Windows_0.geometry}
        material={materials.Windows}
        position={[379.44, 160.96, -3.37]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[46.38, 59.24, 58.29]}
      />
      <mesh
        geometry={nodes.Canopy_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[380.82, 214.55, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[89.09, 100, 100]}
      />
      <mesh
        geometry={nodes.Circle_Metal_black_a_bit_shiny_0.geometry}
        material={materials.Metal_black_a_bit_shiny}
        position={[380.82, 0, 13.58]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={9.02}
      />
      <mesh
        geometry={nodes.Circle001_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[338.61, 96.82, -42.94]}
        rotation={[1.33, -Math.PI / 2, 0]}
        scale={3.5}
      />
      <mesh
        geometry={nodes.Circle002__0.geometry}
        material={materials["Circle.002__0"]}
        position={[367.59, 222.28, 3.01]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[14.02, 23.92, 14.02]}
      />
      <mesh
        geometry={nodes.Clip_wires_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[379.76, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube004_Metal_black_a_bit_shiny_0.geometry}
        material={materials.Metal_black_a_bit_shiny}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[16.06, 5.57, 0.65]}
      />
      <mesh
        geometry={nodes.Cube001_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[365.68, 38.17, 99.29]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[3.39, 1.18, 0.99]}
      />
      <mesh
        geometry={nodes.Cube002_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[365.64, 63.47, 69.43]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[8.77, 3.06, 3.97]}
      />
      <mesh
        geometry={nodes.Cube003_Plastic_matte_0.geometry}
        material={materials.Plastic_matte}
        position={[380.82, 127.36, -82.93]}
        rotation={[-1.83, 0, -Math.PI]}
        scale={[32.01, 18.76, 29.06]}
      />
      <mesh
        geometry={nodes.Cylinder_Metal_black_a_bit_shiny_0.geometry}
        material={materials.Metal_black_a_bit_shiny}
        position={[430.87, 121.39, 67.71]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[-0.71, 0.71, 0.71]}
      />
      <mesh
        geometry={nodes.Cylinder021_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[423.86, 114.06, 58.12]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[2.26, 2.26, 1.56]}
      />
      <mesh
        geometry={nodes.Cylinder028_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder029_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Door_handle_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[353.35, 152.35, 57.85]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Door_keyhole_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[353.35, 159.58, 61.5]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Door_rail_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[344.35, 153.41, 61.05]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={8.76}
      />
      <mesh
        geometry={nodes.Door_rubber_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[380.82, 153.18, 52.87]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[47.03, 59.1, 59.1]}
      />
      <mesh
        geometry={nodes.Engine_top_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[380.82, 138.61, -109.74]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[33.39, 38.65, 38.65]}
      />
      <mesh
        geometry={nodes.Engine_top_grill_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[380.82, 170.34, -103.75]}
        rotation={[-1.71, 0, -Math.PI]}
        scale={[21.15, 9.08, 5.56]}
      />
      <mesh
        geometry={nodes.Exhaust_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[403.01, 160.88, -79.54]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[329.85, 209.01, 242.67]}
      />
      <mesh
        geometry={nodes.Front_detail_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[415.08, 113.03, 69.05]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[2.26, 2.26, 1.56]}
      />
      <mesh
        geometry={nodes.Front_detail001_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[429.57, 117.9, 69.62]}
        rotation={[0, 0, -0.73]}
        scale={[2.67, 2.67, 1.85]}
      />
      <mesh
        geometry={nodes.Front_detail002_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[429.57, 112.91, 68.87]}
        rotation={[0, 0, -1.3]}
        scale={[1.45, 1.45, 1.99]}
      />
      <mesh
        geometry={nodes.Front_detail003_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[429.57, 108.91, 73.25]}
        rotation={[0, 0, -0.73]}
        scale={[2.36, 2.36, 1.64]}
      />
      <mesh
        geometry={nodes.Front_detail_wire_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[415.3, 112.94, 56.93]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={5.27}
      />
      <mesh
        geometry={nodes.Front_light_glass_Roof_front_light_0.geometry}
        material={materials.Roof_front_light}
        position={[380.82, 0, 13.58]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={4.69}
      />
      <mesh
        geometry={nodes.Front_light_housing_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[380.82, 0, 13.58]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={4.69}
      />
      <mesh
        geometry={nodes.Front_plate_Front_CAT_logo_0.geometry}
        material={materials.Front_CAT_logo}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Front_plate001_Metal_yellow_0.geometry}
        material={materials.Metal_yellow}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Front_step_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[380.82, 82.62, 76.77]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[28.61, 22.4, 6.66]}
      />
      <mesh
        geometry={nodes.Front_step_grill_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[380.88, 86.34, 77.33]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[28.61, 22.4, 6.5]}
      />
      <mesh
        geometry={nodes.Grid_Metal_black_a_bit_shiny_0.geometry}
        material={materials.Metal_black_a_bit_shiny}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Lugnuts_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Lugs012_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Lugs_larger_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Lugs_larger001_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[336.61, 159.23, -45.78]}
        rotation={[-1.13, 0, -Math.PI]}
        scale={123.37}
      />
      <mesh
        geometry={nodes.Lugs_larger002_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[381.23, 16.65, -18.67]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Lugs_larger003_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Lugs_larger004_Metal_black_a_bit_shiny_0.geometry}
        material={materials.Metal_black_a_bit_shiny}
        position={[380.82, -0.72, 14.15]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Lugs_larger005_Metal_black_a_bit_shiny_0.geometry}
        material={materials.Metal_black_a_bit_shiny}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Lugs_larger006_Metal_black_a_bit_shiny_0.geometry}
        material={materials.Metal_black_a_bit_shiny}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Lugs_larger007_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[434.56, 127.17, -88.45]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={52.73}
      />
      <mesh
        geometry={nodes.Lugs_larger008_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[356.4, 176.01, -77.75]}
        rotation={[0, -0.44, Math.PI / 2]}
        scale={123.37}
      />
      <mesh
        geometry={nodes.Lugs_larger011_Metal_black_a_bit_shiny_0.geometry}
        material={materials.Metal_black_a_bit_shiny}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Metal_handle_Metal_yellow_0.geometry}
        material={materials.Metal_yellow}
        position={[380.81, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[94.53, 100, 100]}
      />
      <mesh
        geometry={nodes.Metal_handle001_Metal_black_a_bit_shiny_0.geometry}
        material={materials.Metal_black_a_bit_shiny}
        position={[380.81, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[94.53, 100, 100]}
      />
      <mesh
        geometry={nodes.Metal_handle_large_Metal_yellow_0.geometry}
        material={materials.Metal_yellow}
        position={[380.81, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[94.53, 100, 100]}
      />
      <mesh
        geometry={
          nodes.Metal_handle_large001_Metal_black_a_bit_shiny_0.geometry
        }
        material={materials.Metal_black_a_bit_shiny}
        position={[380.81, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[94.53, 100, 100]}
      />
      <mesh
        geometry={
          nodes.Metal_handle_large002_Metal_black_a_bit_shiny_0.geometry
        }
        material={materials.Metal_black_a_bit_shiny}
        position={[380.81, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[94.53, 100, 100]}
      />
      <mesh
        geometry={nodes.MEtal_side_connection_detail_Metal_yellow_0.geometry}
        material={materials.Metal_yellow}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Metal_side_handle_Metal_yellow_0.geometry}
        material={materials.Metal_yellow}
        position={[380.82, 0, 13.58]}
        rotation={[-3.09, 0, -Math.PI]}
        scale={94.98}
      />
      <mesh
        geometry={nodes.Metal_side_handle001_Metal_black_a_bit_shiny_0.geometry}
        material={materials.Metal_black_a_bit_shiny}
        position={[380.82, 0, 13.58]}
        rotation={[-3.09, 0, -Math.PI]}
        scale={94.98}
      />
      <mesh
        geometry={nodes.Metal_side_handle002_Metal_black_a_bit_shiny_0.geometry}
        material={materials.Metal_black_a_bit_shiny}
        position={[380.82, 0, 13.58]}
        rotation={[-3.09, 0, -Math.PI]}
        scale={94.98}
      />
      <mesh
        geometry={nodes.NurbsPath_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[363.96, 38.1, 64.83]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={16.72}
      />
      <mesh
        geometry={nodes.NurbsPath001_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[367.33, 38.1, 64.83]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={16.72}
      />
      <mesh
        geometry={nodes.Plane001_Metal_yellow_0.geometry}
        material={materials.Metal_yellow}
        position={[438.09, 135.34, -83.61]}
        rotation={[-1.52, Math.PI / 2, 0]}
        scale={1.88}
      />
      <mesh
        geometry={nodes.Plane002_Metal_yellow_0.geometry}
        material={materials.Metal_yellow}
        position={[415.37, 112.59, 68.75]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={3.79}
      />
      <mesh
        geometry={nodes.Read_top_bar_arms_Metal_black_a_bit_shiny_0.geometry}
        material={materials.Metal_black_a_bit_shiny}
        position={[380.82, 208.48, -137.43]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[5.1, 5.1, 61.79]}
      />
      <mesh
        geometry={nodes.Rear_arm_connectors_Metal_black_a_bit_shiny_0.geometry}
        material={materials.Metal_black_a_bit_shiny}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Rear_bottom_light_housing_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[380.81, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[94.53, 100, 100]}
      />
      <mesh
        geometry={nodes.Rear_bumper_Metal_yellow_0.geometry}
        material={materials.Metal_yellow}
        position={[380.51, 49.64, -155.11]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[94.53, 113.73, 100]}
      />
      <mesh
        geometry={nodes.Rear_red_light_Rear_red_light_0.geometry}
        material={materials.Rear_red_light}
        position={[380.81, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[94.53, 100, 100]}
      />
      <mesh
        geometry={nodes.Rear_red_round_reflector_Red_matte_0.geometry}
        material={materials.Red_matte}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Rear_side_panels_Metal_yellow_0.geometry}
        material={materials.Metal_yellow}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={
          nodes.Rear_top_bar_cilinders_Metal_black_a_bit_shiny_0.geometry
        }
        material={materials.Metal_black_a_bit_shiny}
        position={[380.82, 0, 13.58]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[28.35, 5.62, 2.02]}
      />
      <mesh
        geometry={nodes.Rear_top_engine_details_Metal_yellow_0.geometry}
        material={materials.Metal_yellow}
        position={[380.82, 0, 13.58]}
        rotation={[-1.97, 0, -Math.PI]}
        scale={32.95}
      />
      <mesh
        geometry={nodes.Rear_top_light_housing_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[380.81, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[94.53, 100, 100]}
      />
      <mesh
        geometry={nodes.Red_metal_detail_side_Red_details_0.geometry}
        material={materials.Red_details}
        position={[338.25, 160.32, -48.31]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={12.14}
      />
      <mesh
        geometry={nodes.Roof_nuts_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Roof_plug_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[343.74, 192.78, -64.7]}
        rotation={[-2.81, 0, Math.PI / 2]}
        scale={[-1.42, 1.42, 1.42]}
      />
      <mesh
        geometry={nodes.Roof_plug_connector_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[380.82, 200.26, -70.51]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={7.47}
      />
      <mesh
        geometry={nodes.Seat_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[380.82, 130.23, -42.91]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[22.69, 6.87, 25.21]}
      />
      <mesh
        geometry={nodes.Seat_plate_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[380.82, 89.61, -6.52]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[32.81, 32.81, 10.37]}
      />
      <mesh
        geometry={nodes.Shovel_Metal_black_a_bit_shiny_0.geometry}
        material={materials.Metal_black_a_bit_shiny}
        position={[380.82, 27.71, 125.66]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Shovel_arm_details_connectors_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Shovel_arm_details_connectors001_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Shovel_arm_wires_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Shovel_arm_wires001_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Shovel_mount_Metal_black_a_bit_shiny_0.geometry}
        material={materials.Metal_black_a_bit_shiny}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Shovel_small_handles_Metal_yellow_0.geometry}
        material={materials.Metal_yellow}
        position={[380.82, 0, 208.94]}
        rotation={[-3.09, 0, -Math.PI]}
        scale={94.98}
      />
      <mesh
        geometry={nodes.Side_metal_bar_Red_details_0.geometry}
        material={materials.Red_details}
        position={[432.86, 126.05, -63.17]}
        rotation={[-1.53, 0, -Math.PI]}
        scale={[28.03, 41.38, 3.73]}
      />
      <mesh
        geometry={nodes.Side_panel001_Metal_yellow_0.geometry}
        material={materials.Metal_yellow}
        position={[380.8, 0, 13.58]}
        rotation={[-1.57, 0, 3.14]}
        scale={100}
      />
      <mesh
        geometry={nodes.Side_plate_Metal_yellow_0.geometry}
        material={materials.Metal_yellow}
        position={[380.82, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Sphere001_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[367.59, 212.44, 2.81]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[7.03, 7.03, 7.48]}
      />
      <mesh
        geometry={nodes.Steering_controls_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[380.67, -1.15, 13.66]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Triangle_back_plate_Metal_yellowCAT_logo001_0.geometry}
        material={materials["Metal_yellow.CAT_logo.001"]}
        position={[380.81, 101.69, -153.26]}
        rotation={[-1.65, 0, -Math.PI]}
        scale={[101.92, 100, 100]}
      />
      <mesh
        geometry={nodes.white_lens_rear_light_Rear_white_light_0.geometry}
        material={materials.Rear_white_light}
        position={[380.81, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[94.53, 100, 100]}
      />
      <mesh
        geometry={nodes.wiper_housing_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[412.1, 151.92, 55.68]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-1.14, 1.14, 1.14]}
      />
      <mesh
        geometry={nodes.Wire_roof_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[374.61, 163.54, -70.18]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.21}
      />
      <mesh
        geometry={nodes.Wires_side_Nuts_grey_0.geometry}
        material={materials.material_0}
        position={[379.93, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Wires_side001_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[379.93, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Wires_side002_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[379.93, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Wires_side_plate_Metal_yellow_0.geometry}
        material={materials.Metal_yellow}
        position={[379.43, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Wires_tiop_side_Plastic_matte001_0.geometry}
        material={materials["Plastic_matte.001"]}
        position={[379.9, 0, 13.58]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/scene.gltf");
